/**
 * Event types shown in project/dashboard activity filter panels.
 * String literals — safe for client bundles (do not import Prisma enums here).
 */
export const FILTERABLE_ACTIVITY_EVENT_TYPES = [
  "SCOPE_STATUS_UPDATED",
  "SCOPE_STATUS_BULK_UPDATED",
  "SCOPE_STATUS_BULK_UNDONE",
  "SCOPE_INSPECTION_UPDATED",
  "SCOPE_INSPECTION_BULK_UPDATED",
  "INSPECTION_BACKFILL_SET",
  "INSPECTION_BACKFILL_DELETED",
  "INSPECTION_SUBMITTED",
  "INSPECTION_SYNC_FAILED",
  "MUTATION_SYNC_FAILED",
  "ISSUE_CREATED",
  "ISSUE_BULK_CREATED",
  "ISSUE_UPDATED",
  "ISSUE_DELETED",
  "ISSUE_RESOLVED",
  "ISSUE_REOPENED",
  "OBSERVATION_CREATED",
  "OBSERVATION_BULK_CREATED",
  "OBSERVATION_UPDATED",
  "UNIT_PHOTO_UPLOADED",
  "SCOPE_SUBCONTRACTOR_UPDATED",
  "SUB_SCOPE_INSTANCE_UPDATED",
] as const;

export type FilterableActivityEventType = (typeof FILTERABLE_ACTIVITY_EVENT_TYPES)[number];
