/**
 * Mock Unifier data for local + dev when UNIFIER_MOCK=true.
 *
 * Project data shape matches UnifierProject (normalized from UNIFIER_US_XPRJ):
 * pid, projectNumber, projectName, status, location, address, state, clientName,
 * (`location` and `address` both mirror CP_GEN_ADDRESS_TB2000 — not UUU_LOCATION.)
 * projectType, projectPhase, stage, estimatingStage, projectManagerName,
 * estimatorName, fieldDueDate, sageProjectId, rfmsProjectId, projectTrack.
 *
 * `status` mirrors `CP_PROJECT_PHASEPD` (phase string). `shellStatus` mirrors `UUU_SHELL_STATUS`
 * (Active / inactive / etc.) for mapping Field Tracker project status on import.
 */

import type { UnifierProject } from "./types";

/** Raw UNIFIER_UXSUB rows — only fields needed by getSubcontractorsForPicker(). */
export const MOCK_UNIFIER_SUBCONTRACTORS: Record<string, unknown>[] = [
  {
    ID: "MOCK-SUB-001",
    STATUS: "Active",
    CP_SUB_SUBCONTRACTNAME_TB50: "Apex Flooring LLC",
    CP_SUB_COSHORTNAME_TB60: "Apex Flooring",
  },
  {
    ID: "MOCK-SUB-002",
    STATUS: "Active",
    CP_SUB_SUBCONTRACTNAME_TB50: "Summit Electrical Services",
    CP_SUB_COSHORTNAME_TB60: "Summit Electric",
  },
  {
    ID: "MOCK-SUB-003",
    STATUS: "Active",
    CP_SUB_SUBCONTRACTNAME_TB50: "Premier Cabinets & Millwork",
    CP_SUB_COSHORTNAME_TB60: "Premier Cabinets",
  },
  {
    ID: "MOCK-SUB-INACTIVE",
    STATUS: "Inactive",
    CP_SUB_SUBCONTRACTNAME_TB50: "Legacy Drywall Co",
    CP_SUB_COSHORTNAME_TB60: "Legacy Drywall",
  },
];

export const MOCK_UNIFIER_PROJECTS: UnifierProject[] = [
  {
    pid: "UNI-10045",
    projectNumber: "2024-0045",
    projectName: "Riverside Apartments Phase 2",
    shellStatus: "Active",
    status: "Construction",
    location: "1200 Riverside Dr",
    address: "1200 Riverside Dr",
    state: "TX",
    clientName: "Riverside Development LLC",
    projectType: "Multi-Family Residential",
    projectPhase: "Construction",
    stage: "Execution",
    estimatingStage: null,
    projectManagerName: "Sarah Johnson",
    estimatorName: "Tom Bradley",
    fieldDueDate: "2025-08-15",
    sageProjectId: "SAG-2024-0045",
    rfmsProjectId: "RFMS-0045",
    projectTrack: "Standard",
  },
  {
    pid: "UNI-10032",
    projectNumber: "2024-0032",
    projectName: "Downtown Office Complex",
    shellStatus: "Active",
    status: "Construction",
    location: "500 Commerce St",
    address: "500 Commerce St",
    state: "TX",
    clientName: "Commerce Tower Partners",
    projectType: "Commercial Office",
    projectPhase: "Construction",
    stage: "Execution",
    estimatingStage: null,
    projectManagerName: "Emily Rodriguez",
    estimatorName: "James Carter",
    fieldDueDate: "2025-06-30",
    sageProjectId: "SAG-2024-0032",
    rfmsProjectId: "RFMS-0032",
    projectTrack: "Standard",
  },
  {
    pid: "UNI-10189",
    projectNumber: "2023-0189",
    projectName: "Oak Grove Residences",
    shellStatus: "Inactive",
    status: "Closeout",
    location: "800 Oak Grove Blvd",
    address: "800 Oak Grove Blvd",
    state: "TX",
    clientName: "Oak Grove Properties",
    projectType: "Multi-Family Residential",
    projectPhase: "Closeout",
    stage: "Complete",
    estimatingStage: null,
    projectManagerName: "David Martinez",
    estimatorName: "Tom Bradley",
    fieldDueDate: "2024-11-01",
    sageProjectId: "SAG-2023-0189",
    rfmsProjectId: "RFMS-0189",
    projectTrack: "Standard",
  },
  {
    pid: "UNI-10067",
    projectNumber: "2024-0067",
    projectName: "Sunset Plaza Renovation",
    shellStatus: "Active",
    status: "Construction",
    location: "2400 Sunset Blvd",
    address: "2400 Sunset Blvd",
    state: "TX",
    clientName: "Sunset Commercial Group",
    projectType: "Renovation",
    projectPhase: "Construction",
    stage: "Execution",
    estimatingStage: null,
    projectManagerName: "Sarah Johnson",
    estimatorName: "Maria Nguyen",
    fieldDueDate: "2025-09-20",
    sageProjectId: "SAG-2024-0067",
    rfmsProjectId: "RFMS-0067",
    projectTrack: "Standard",
  },
  {
    pid: "UNI-10145",
    projectNumber: "2023-0145",
    projectName: "Marina Bay Condos",
    shellStatus: "Inactive",
    status: "Closeout",
    location: "350 Marina Bay Dr",
    address: "350 Marina Bay Dr",
    state: "TX",
    clientName: "Coastal Living Developments",
    projectType: "Multi-Family Residential",
    projectPhase: "Closeout",
    stage: "Complete",
    estimatingStage: null,
    projectManagerName: "Robert Kim",
    estimatorName: "James Carter",
    fieldDueDate: "2024-09-10",
    sageProjectId: "SAG-2023-0145",
    rfmsProjectId: "RFMS-0145",
    projectTrack: "Standard",
  },
  {
    pid: "UNI-10089",
    projectNumber: "2024-0089",
    projectName: "Tech Hub Building 3",
    shellStatus: "Active",
    status: "Construction",
    location: "1100 Innovation Pkwy",
    address: "1100 Innovation Pkwy",
    state: "TX",
    clientName: "Innovation Campus LLC",
    projectType: "Commercial Office",
    projectPhase: "Construction",
    stage: "Execution",
    estimatingStage: null,
    projectManagerName: "Emily Rodriguez",
    estimatorName: "Maria Nguyen",
    fieldDueDate: "2025-11-30",
    sageProjectId: "SAG-2024-0089",
    rfmsProjectId: "RFMS-0089",
    projectTrack: "Standard",
  },
  {
    pid: "UNI-10112",
    projectNumber: "2024-0112",
    projectName: "Northgate Medical Center",
    shellStatus: "Active",
    status: "Construction",
    location: "720 Northgate Medical Dr",
    address: "720 Northgate Medical Dr",
    state: "TX",
    clientName: "Northgate Health Systems",
    projectType: "Healthcare",
    projectPhase: "Construction",
    stage: "Execution",
    estimatingStage: null,
    projectManagerName: "David Martinez",
    estimatorName: "Tom Bradley",
    fieldDueDate: "2025-12-15",
    sageProjectId: "SAG-2024-0112",
    rfmsProjectId: "RFMS-0112",
    projectTrack: "Standard",
  },
  {
    pid: "UNI-10203",
    projectNumber: "2025-0003",
    projectName: "Lakeside Senior Living",
    shellStatus: "Planning",
    status: "Pre-Construction",
    location: "555 Lakeside Pkwy",
    address: "555 Lakeside Pkwy",
    state: "TX",
    clientName: "Lakeside Senior Partners",
    projectType: "Senior Housing",
    projectPhase: "Pre-Construction",
    stage: "Planning",
    estimatingStage: "Preliminary Estimate",
    projectManagerName: "Sarah Johnson",
    estimatorName: "James Carter",
    fieldDueDate: null,
    sageProjectId: null,
    rfmsProjectId: null,
    projectTrack: "Standard",
  },
];

