/**
 * Unifier PDS table schema definitions.
 *
 * This is the authoritative source for all available Unifier tables and their columns.
 * It is used by the DevTools Unifier Explorer panel and the /api/devtools/unifier-explore
 * allowlist to prevent arbitrary table injection.
 *
 * Source: Tosh (VI) — provided column lists for Oracle Primavera Unifier PDS API.
 * Tables marked `integrated: true` already have production service wiring.
 */

export interface UnifierColumnDef {
  /** Unifier internal column code (used in PDS queries) */
  code: string;
  /** Human-readable label */
  label: string;
}

export interface UnifierTableDef {
  /** Unifier internal table name (used in PDS queries) */
  tableName: string;
  /** Human-readable display name */
  displayName: string;
  /** Short description of what this table contains */
  description: string;
  /** Column definitions */
  columns: UnifierColumnDef[];
  /** Whether this table already has a production service/route wired up */
  integrated?: boolean;
  /** Whether this table has line items (child table) */
  isLineItem?: boolean;
}

export const UNIFIER_SCHEMA: UnifierTableDef[] = [
  // ── Already integrated ────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_US_XPRJ",
    displayName: "Project Shells",
    description: "All Unifier project shells — the top-level project records.",
    integrated: true,
    columns: [
      { code: "PID", label: "Project ID" },
      { code: "UE_PRJ_PROJNAMESSN", label: "Project Name" },
      { code: "UE_PRJ_PROJNUMSSN", label: "Project Number" },
      { code: "UUU_SHELL_STATUS", label: "Shell Status" },
      { code: "UUU_LOCATION", label: "Location" },
      { code: "CP_GEN_ADDRESS_TB2000", label: "Address" },
      { code: "CP_GEN_STATE_PD", label: "State" },
      { code: "CP_CL_CLIENTNAME_TB50", label: "Client Name" },
      { code: "CP_OP_PROJECTTYPE_PD", label: "Project Type" },
      { code: "CP_PROJECT_PHASEPD", label: "Project Phase" },
      { code: "CP_OP_STAGE_PD", label: "Stage" },
      { code: "CP_OP_ESTIMATINGSTAGE_PD", label: "Estimating Stage" },
      { code: "CP_GEN_PROJMANAGER_NAME", label: "Project Manager Name" },
      { code: "CP_GEN_ESTIMATOR_NAME", label: "Estimator Name" },
      { code: "CP_OP_FDD_DOP", label: "Field Due Date" },
      { code: "CP_AP_SAGEPROJECTID_TB", label: "Sage Project ID" },
      { code: "CP_AP_RFMSPROJECTID_TB", label: "RFMS Project ID" },
      { code: "CP_OP_PROJECTTRACK_PD", label: "Project Track" },
    ],
  },

  {
    tableName: "UNIFIER_UXPT",
    displayName: "Project Team Assignments",
    description: "Project team member roles and assignments per project.",
    integrated: true,
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "STATUS", label: "Status" },
      { code: "TITLE", label: "Title" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "CP_GEN_PREESTIMATOR_NAME", label: "Pre-Estimator Name" },
      { code: "CP_OP_PREESTIMATOR_DP", label: "Pre-Estimator ID" },
      { code: "CP_GEN_SALES_NAME", label: "Sales Name" },
      { code: "CP_GEN_SALES_UP", label: "Sales ID" },
      { code: "CP_GEN_PROJMANAGER_NAME", label: "Project Manager Name" },
      { code: "CP_OP_PROJECTMANAGER_DP", label: "Project Manager ID" },
      { code: "CP_GEN_DRAFTSMAN_NAME", label: "Draftsman Name" },
      { code: "CP_GEN_DRAFTSMAN_UP", label: "Draftsman ID" },
      { code: "CP_GEN_PRJCOORDINATOR_NAME", label: "Project Coordinator Name" },
      { code: "CP_OP_PROJECTCOORDINATOR_DP", label: "Project Coordinator ID" },
      { code: "CP_GEN_ORDERSPECIALIST_NAME", label: "Order Specialist Name" },
      { code: "CP_ORDERSPECIALIST_UP", label: "Order Specialist ID" },
      { code: "CP_GEN_QUALITYCONTROL_NAME", label: "Quality Control Name" },
      { code: "CP_GEN_QUALITYCONTROL_UP", label: "Quality Control ID" },
      { code: "CP_GEN_PROJENGINEER_NAME", label: "Project Engineer Name" },
      { code: "CP_GEN_PROJECTENGINEER_UP", label: "Project Engineer ID" },
      { code: "CP_GEN_INSTALLATIONMGR_UP", label: "Install Manager ID" },
      { code: "CP_GEN_INSTALLMANAGER_NAME", label: "Install Manager Name" },
      { code: "CP_GEN_ACCOUNTING_NAME", label: "Accounting Name" },
      { code: "CP_GEN_ACCOUNTING_UP", label: "Accounting ID" },
      { code: "CP_GEN_PROJECTCONTROLS_NAME", label: "Project Controls Name" },
      { code: "CP_GEN_PROJECTCONTROLS_UP", label: "Project Controls ID" },
      { code: "CP_GEN_SCHEDULING_NAME", label: "Scheduling Name" },
      { code: "CP_GEN_SCHEDULING_UP", label: "Scheduling ID" },
      { code: "CP_GEN_ESTIMATOR_NAME", label: "Estimator Name" },
      { code: "CP_OP_ESTIMATOR_DP", label: "Estimator ID" },
      { code: "CP_GEN_COSTENGINEER_NAME", label: "Cost Engineer Name" },
      { code: "CP_OP_COSTENGINEER_DP", label: "Cost Engineer ID" },
      { code: "CP_OP_PROJECTOWNERNAME_SMN", label: "Project Owner Name" },
      { code: "CP_OP_OPPOWNER_DP", label: "Project Owner ID" },
    ],
  },

  // ── Users ────────────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_SYS_USER_INFO",
    displayName: "Users",
    description: "All Unifier user accounts — used for linking Field Tracker users to Unifier identities.",
    columns: [
      { code: "USERID", label: "User ID" },
      { code: "USERNAME", label: "Username" },
      { code: "FULLNAME", label: "Full Name" },
      { code: "EMAIL", label: "Email" },
      { code: "TITLE", label: "Title / Job Title" },
      { code: "CREATEDATE", label: "Created Date" },
    ],
  },

  // ── Project Info ──────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_SYS_PROJECT_INFO",
    displayName: "Project Info (System)",
    description: "System-level project metadata including phase, manager, and completion dates.",
    columns: [
      { code: "PID", label: "Project ID" },
      { code: "PROJECTNUMBER", label: "Project Number" },
      { code: "PROJECTNAME", label: "Project Name" },
      { code: "PROJECTTYPE", label: "Project Type" },
      { code: "PROJECTPHASE", label: "Project Phase" },
      { code: "STATUS", label: "Status" },
      { code: "ACTIVE", label: "Active" },
      { code: "STARTDATE", label: "Start Date" },
      { code: "PLANNEDCOMPLETION", label: "Planned Completion" },
      { code: "CREATEDATE", label: "Created Date" },
      { code: "MANAGERID", label: "Manager ID" },
    ],
  },

  // ── Daily Activity Reports ────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXUEDR",
    displayName: "Daily Activity Reports",
    description: "Daily workforce activity logs per project — hours, workforce counts, PM and IM assignments.",
    columns: [
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UE_DAR_DAILYACTDATEDO", label: "Daily Activity Date" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "STATUS", label: "Status" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UE_DAR_TOTWORKFORCEDA", label: "Total Workforce (Daily)" },
      { code: "UE_DAR_TOTWORKFORCEHOURSDA", label: "Total Workforce Hours (Daily)" },
      { code: "CP_OP_PROJECTMANAGER_DP", label: "Project Manager ID" },
      { code: "CP_GEN_INSTALLATIONMGR_UP", label: "Install Manager ID" },
    ],
  },

  // ── Inspections ───────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXTACIN",
    displayName: "Turn-Around Inspections",
    description: "Unit-level turn-around inspection records with pass/fail/NA counts per inspection item.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "UE_PRJ_PROJNAMESSN", label: "Project Name" },
      { code: "UE_PRJ_PROJNUMSSN", label: "Project Number" },
      { code: "CP_CI_UNIT_TB", label: "Unit" },
      { code: "CP_CI_BUILDING_PD", label: "Building" },
      { code: "CP_CI_LEVEL_DA", label: "Level (numeric)" },
      { code: "CP_CI_LEVEL_TB", label: "Level" },
      { code: "CP_CI_AREA_PD", label: "Area" },
      { code: "CP_CI_PHASE_TB", label: "Phase" },
      { code: "CP_CI_LOCATIONS_DP", label: "Locations" },
      { code: "CP_CI_INSPECTIONREVISION_TB", label: "Inspection Revision" },
      { code: "CP_CI_TYPE_PD", label: "Inspection Type" },
      { code: "CP_CI_SUMMARYPASS_DA", label: "Summary Pass Count" },
      { code: "CP_CI_SUMMARYFAIL_DA", label: "Summary Fail Count" },
      { code: "CP_CI_SUMMARYNA_DA", label: "Summary N/A Count" },
      { code: "CP_AC_ASSIGNEES_TB255", label: "Assignees" },
      { code: "CP_2A_CABINETS_DP", label: "Cabinets" },
      { code: "CP_2A_COUNTERTOPS_DP", label: "Countertops" },
      { code: "CP_2A_HARDSURFACE_DP", label: "Hard Surface" },
      { code: "CP_2A_TILE_DP", label: "Tile" },
      { code: "CP_2A_CARPETTILE_DP", label: "Carpet Tile" },
      { code: "CP_2A_CARPETBROADLOOM_DP", label: "Carpet Broadloom" },
    ],
  },

  {
    tableName: "UNIFIER_UXCLEARI",
    displayName: "Clearance Inspections",
    description: "Unit-level clearance inspection records for final sign-off.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "DUE_DATE", label: "Due Date" },
      { code: "END_DATE", label: "End Date" },
      { code: "UE_PRJ_PROJNUMSSN", label: "Project Number" },
      { code: "UE_GEN_PROJNAMESSN", label: "Project Name" },
      { code: "CP_CI_UNIT_TB", label: "Unit" },
      { code: "CP_CI_BUILDING_PD", label: "Building" },
      { code: "CP_CI_LEVEL_DA", label: "Level (numeric)" },
      { code: "CP_CI_LEVEL_TB", label: "Level" },
      { code: "CP_CI_AREA_PD", label: "Area" },
      { code: "CP_CI_PHASE_TB", label: "Phase" },
      { code: "CP_CI_LOCATIONS_DP", label: "Locations" },
      { code: "CP_CI_INSPECTIONREVISION_TB", label: "Inspection Revision" },
      { code: "CP_CI_SUMMARYPASS_DA", label: "Summary Pass Count" },
      { code: "CP_CI_SUMMARYFAIL_DA", label: "Summary Fail Count" },
      { code: "CP_CI_SUMMARYNA_DA", label: "Summary N/A Count" },
      { code: "CP_AC_TRADE_PD", label: "Trade" },
      { code: "CP_AC_CREATEDBY_UP", label: "Created By" },
      { code: "CP_PHASE_PLAN_PD", label: "Phase Plan" },
      { code: "CP_CI_ATTACHMENTS_TB", label: "Attachments" },
    ],
  },

  // ── Project Status Reports ────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXPSR",
    displayName: "Project Status Reports",
    description: "Periodic status reports with G/Y/R health indicators, financials, and narrative summaries.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "UE_PRS_PROJREPORTINGDATEDO", label: "Reporting Date" },
      { code: "CP_PROJECT_PHASEPD", label: "Project Phase" },
      { code: "UUU_PROJECT_START_DATE", label: "Project Start Date" },
      { code: "CP_OP_FDD_DOP", label: "Field Due Date (Manual)" },
      { code: "CP_PSR_OVERALLSTATUS_PD", label: "Overall Status (G/Y/R)" },
      { code: "UE_PRJ_PROJPERCCOMLDA", label: "Percent Complete" },
      { code: "CP_PSR_SCHEDULESTATUS_DOP", label: "Substantial Completion Date" },
      { code: "CP_PSR_SCHEDULESTATUS_PD", label: "Schedule Status (G/Y/R)" },
      { code: "CP_PSR_SCHEDULSTATUSNARR_TB", label: "Schedule Status Narrative" },
      { code: "CP_PSR_COSTSTATUS_PD", label: "Cost Status (G/Y/R)" },
      { code: "CP_PSR_COSTSTATUSNARRATI_TB", label: "Cost Status Narrative" },
      { code: "CP_PSR_QUALITYSTATUS_PD", label: "Quality Status (G/Y/R)" },
      { code: "CP_PSR_QUALSTATUSNARRATI_TB", label: "Quality Status Narrative" },
      { code: "CP_PSR_RISKSTATUS_PD", label: "Risk Status (G/Y/R)" },
      { code: "CP_PSR_RISKSTATUSNARRATI_TB", label: "Risk Status Narrative" },
      { code: "CP_GEN_PROJMANAGER_NAME", label: "Project Manager Name" },
      { code: "CP_OP_PROJECTMANAGER_DP", label: "Project Manager ID" },
      { code: "CP_GEN_SALES_NAME", label: "Sales Name" },
      { code: "CP_GEN_SALES_UP", label: "Sales ID" },
      { code: "CP_GEN_INSTALLMANAGER_NAME", label: "Install Manager Name" },
      { code: "CP_GEN_INSTALLATIONMGR_UP", label: "Install Manager ID" },
      { code: "CP_GEN_ESTIMATOR_NAME", label: "Estimator Name" },
      { code: "CP_OP_ESTIMATOR_DP", label: "Estimator ID" },
      { code: "CP_GEN_PRJCOORDINATOR_NAME", label: "Project Coordinator Name" },
      { code: "CP_OP_PROJECTCOORDINATOR_DP", label: "Project Coordinator ID" },
      { code: "CP_PSR_SCOPE_TB4000", label: "Scope" },
      { code: "UE_PRS_WORKCMPLLSTPERMB4000", label: "Work Completed Last Period" },
      { code: "UE_PRS_PLANNEXTSTATUSMB4000", label: "Plan for Next Period" },
      { code: "CP_PSR_HELPNEEDED_TB4000", label: "Help Needed" },
      { code: "CP_PSR_ORIGINALCONTRACT_CUR", label: "Original Contract Value" },
      { code: "CP_PSR_ORIGINALCOSTBDGT_CUR", label: "Original Cost Budget" },
      { code: "CP_PSR_APPROVEDCO_CUR", label: "Approved Change Order Value" },
      { code: "CP_PSR_CURRENTCOST_CURR", label: "Current Cost" },
      { code: "CP_PSR_CURRENTCONTRACT_CA", label: "Current Contract Value" },
      { code: "CP_PSR_ORIGINALGP_CA", label: "Original Gross Profit" },
      { code: "CP_PSR_PENDINGCO_CA", label: "Pending Change Order Value" },
      { code: "CP_PSR_ORIGINALGM_DA", label: "Original Gross Margin %" },
      { code: "CP_PSR_POTENTIALCONTRACT_CA", label: "Potential Contract Value" },
      { code: "CP_PSR_CURRENTGP_CA", label: "Current Gross Profit" },
      { code: "CP_PSR_CURRENTGM_DA", label: "Current Gross Margin %" },
    ],
  },

  // ── Contracts ─────────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXUECON",
    displayName: "Contracts",
    description: "Contract records — amounts, margins, client info, work type, and project linkage.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "UE_CON_CONNUMTB50", label: "Contract Number" },
      { code: "UE_CON_CONNUMTITLETB255", label: "Contract Number + Title" },
      { code: "CP_CL_CLIENTNAME_TB50", label: "Client Name" },
      { code: "CP_CON_CLIENT_DP", label: "Client ID" },
      { code: "AMOUNT", label: "Amount" },
      { code: "CP_CON_CONTRACTAMOUNT_CA", label: "Contract Amount" },
      { code: "UE_CON_ORIGCOMMCA", label: "Original Commitment" },
      { code: "UE_CON_REVCOMMABCA", label: "Revised Commitment A+B" },
      { code: "UE_CON_BALTOFININCLRETCA", label: "Balance to Finish (incl. Retainage)" },
      { code: "CP_OP_NOOFUNITS_IA", label: "Number of Units" },
      { code: "CP_OP_PROJECTTYPE_PD", label: "Project Type" },
      { code: "CP_CON_WORKTYPE_PD", label: "Work Type" },
      { code: "CP_OP_STAGE_PD", label: "Stage" },
      { code: "CP_OP_FLOORINGAMOUNT_CA", label: "Flooring Amount" },
      { code: "CP_OP_BUILDAMOUNT_CA", label: "Build Amount" },
      { code: "CP_OP_DOORAMOUNT_CA", label: "Door Amount" },
      { code: "CP_OP_GENERALCOST_CA", label: "General Cost" },
      { code: "CP_OP_FLOORCOST_CA", label: "Floor Cost" },
      { code: "CP_OP_BUILDCOST_CA", label: "Build Cost" },
      { code: "CP_OP_DOORCOST_CA", label: "Door Cost" },
      { code: "CP_OP_FLOORMARGIN_CA", label: "Floor Margin" },
      { code: "CP_OP_BUILDMARGIN_CA", label: "Build Margin" },
      { code: "CP_OP_DOORMARGIN_CA", label: "Door Margin" },
      { code: "CP_OP_GENMARGIN_CA", label: "General Margin" },
      { code: "CP_OP_GROSSMARGIN_DA", label: "Gross Margin %" },
      { code: "CP_OP_PROFITMARGIN_CA", label: "Profit Margin" },
      { code: "CP_GEN_STATE_PD", label: "State" },
      { code: "CP_GEN_ADDRESS_TB2000", label: "Address" },
      { code: "CP_GEN_CITY_TB50", label: "City" },
      { code: "CP_GEN_ESTIMATOR_NAME", label: "Estimator Name" },
      { code: "CP_OP_ESTIMATOR_DP", label: "Estimator ID" },
      { code: "DUE_DATE", label: "Due Date" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXUECON_LINEITEM",
    displayName: "Contract Line Items",
    description: "Line items within contract records — scope breakdown, costs, and margins.",
    isLineItem: true,
    columns: [
      { code: "ID", label: "ID" },
      { code: "RECORD_ID", label: "Parent Record ID" },
      { code: "LI_NUM", label: "Line Item Number" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "SHORT_DESC", label: "Short Description" },
      { code: "AMOUNT", label: "Amount" },
      { code: "UUU_QUANTITY", label: "Quantity" },
      { code: "UUU_UNIT_PRICE", label: "Unit Price" },
      { code: "UE_CD_UNITPRICECA", label: "Unit Price (CA)" },
      { code: "UE_GEN_UNITOFMEASURESPD", label: "Unit of Measure" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "CP_OP_FLOORINGAMOUNT_CA", label: "Flooring Amount" },
      { code: "CP_OP_BUILDAMOUNT_CA", label: "Build Amount" },
      { code: "CP_OP_DOORAMOUNT_CA", label: "Door Amount" },
      { code: "CP_OP_FLOORCOST_CA", label: "Floor Cost" },
      { code: "CP_OP_BUILDCOST_CA", label: "Build Cost" },
      { code: "CP_OP_DOORCOST_CA", label: "Door Cost" },
      { code: "CP_OP_FLOORMARGIN_CA", label: "Floor Margin" },
      { code: "CP_OP_BUILDMARGIN_CA", label: "Build Margin" },
      { code: "CP_OP_DOORMARGIN_CA", label: "Door Margin" },
      { code: "CP_OP_GENMARGIN_CA", label: "General Margin" },
      { code: "CP_OP_GROSSMARGIN_DA", label: "Gross Margin %" },
      { code: "CP_OP_PROFITMARGIN_CA", label: "Profit Margin" },
      { code: "GROUP_ID", label: "Group ID" },
      { code: "GROUP_TYPE", label: "Group Type" },
      { code: "BUDGETID", label: "Budget ID" },
      { code: "UUU_LI_LAST_UPDATE_DATE", label: "Last Updated" },
    ],
  },

  // ── Potential Change Orders ────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXPCO",
    displayName: "Potential Change Orders (PCOs)",
    description: "Potential change order records — proposed scope changes with cost and schedule impacts.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "UE_PRJ_PROJNAMESSN", label: "Project Name" },
      { code: "AMOUNT", label: "Amount" },
      { code: "CP_PCO_DECISION_PD", label: "Decision" },
      { code: "CP_PCO_CURRENTSTATUS_TB", label: "Current Status" },
      { code: "CP_PCO_CLOSEDATE_DOP", label: "Close Date" },
      { code: "CP_PCO_QUOTEISSUE_DOP", label: "Quote Issue Date" },
      { code: "CP_PCO_QUOTEVALIDTHRU_DOP", label: "Quote Valid Through" },
      { code: "CP_PCO_PROJECTTYPE_PD", label: "Work Type" },
      { code: "CP_PCO_SHOPDRAWINGS_PD", label: "Shop Drawings" },
      { code: "CP_PCO_CONTRACTNO_DP", label: "Contract Number" },
      { code: "UE_GEN_CHGREASONIPD", label: "Change Reason" },
      { code: "CP_CO_CLIENTCO_DP", label: "Client CO Number" },
      { code: "CP_CL_CLIENTNAME_TB50", label: "Client Name" },
      { code: "CP_GEN_PROJMANAGER_NAME", label: "Project Manager Name" },
      { code: "CP_PCO_PMEMAIL_TB64", label: "PM Email" },
      { code: "CP_PCO_PMPHONE_TB64", label: "PM Phone" },
      { code: "UE_GEN_SHORTDESCTB250", label: "Short Description" },
      { code: "CP_PCO_NOTES_TB4000", label: "Notes" },
      { code: "CP_PCO_EXCLUSIONS_TB4000", label: "Exclusions" },
      { code: "CP_PCO_MARGINSTRATEGY_TB", label: "Margin Strategy" },
      { code: "UE_PCO_PROPPCOESTCA", label: "Proposed CO Estimate" },
      { code: "UE_RFI_PRESTSCHEDIMPDAYSIA", label: "Proposed Schedule Impact (Days)" },
      { code: "UE_CON_ORIGCOMMCA", label: "Original Commitment" },
      { code: "UE_CO_PREVAPPCOSQBDE", label: "Previously Approved COs" },
      { code: "UE_CO_CURRREQCA", label: "Current Request" },
      { code: "UE_CON_CONNUMTB50", label: "Contract Number" },
      { code: "CP_OP_BUILDMARGIN_CA", label: "Build Margin" },
      { code: "CP_OP_FLOORMARGIN_CA", label: "Floor Margin" },
      { code: "CP_OP_DOORMARGIN_CA", label: "Door Margin" },
      { code: "CP_OP_GENMARGIN_CA", label: "General Margin" },
      { code: "CP_GEN_STATE_PD", label: "State" },
      { code: "CP_GEN_ADDRESS_TB2000", label: "Address" },
      { code: "CP_GEN_CITY_TB50", label: "City" },
    ],
  },

  // ── Subcontractors ────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXSUB",
    displayName: "Subcontractors",
    description: "Subcontractor directory — contact info, licensing, insurance, and prequalification status.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "CP_SUB_SUBCONTRACTNAME_TB50", label: "Subcontractor Name" },
      { code: "CP_SUB_COSHORTNAME_TB60", label: "Short Name" },
      { code: "CP_PRJ_LEGALSUBNAME_TB255", label: "Legal Name" },
      { code: "CP_GEN_SUBFIRSTNAME_TB64", label: "Contact First Name" },
      { code: "CP_GEN_SUBCONLASTNAME_TB64", label: "Contact Last Name" },
      { code: "CP_SUB_PHONE_TB64", label: "Phone" },
      { code: "CP_GEN_SUBCONTACTPHONE_TB64", label: "Contact Phone" },
      { code: "UE_BLD_PRIMCNTACTEMAILTB128", label: "Primary Contact Email" },
      { code: "CP_GEN_ADDRESS_TB2000", label: "Address" },
      { code: "CP_GEN_CITY_TB50", label: "City" },
      { code: "CP_GEN_STATE_PD", label: "State" },
      { code: "CP_GEN_ZIP_TB16", label: "Zip Code" },
      { code: "CP_SUB_PRIMDISCIPLINE_PD", label: "Primary Discipline" },
      { code: "CP_SUB_PREQUALIFIED_RB", label: "Pre-Qualified" },
      { code: "CP_SUB_TAXID_TB16", label: "Tax ID" },
      { code: "CP_SUB_LICENSENO_TB255", label: "License Number" },
      { code: "CP_SUB_EXPIRATIONDATE_DOP", label: "License Expiration Date" },
      { code: "CP_SUB_POLICYNUM_TB32", label: "Insurance Policy Number" },
      { code: "CP_SUB_POLICYEFFDATE_DOP", label: "Policy Effective Date" },
      { code: "CP_SUB_POLICYEXPIRATION_DOP", label: "Policy Expiration Date" },
      { code: "CP_SUB_INSPROVIDER_TB32", label: "Insurance Provider" },
      { code: "CP_SUB_WCPOLICYNUM_TB32", label: "Workers Comp Policy Number" },
      { code: "CP_SUB_WCPOLICYEFFDATE_DOP", label: "Workers Comp Effective Date" },
      { code: "CP_SUB_WCPOLICYEXPIR_DOP", label: "Workers Comp Expiration Date" },
      { code: "CP_SUB_WCINSPROVIDER_TB32", label: "Workers Comp Insurance Provider" },
      { code: "CP_SUB_SUBTAGS_TB4000", label: "Tags" },
    ],
  },

  // ── Purchase Orders (Subcontractor) ──────────────────────────────────────

  {
    tableName: "UNIFIER_UXPOS",
    displayName: "Subcontractor Purchase Orders",
    description: "Purchase orders issued to subcontractors — amounts, status, and payment terms.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "UE_PRJ_PROJNAMESSN", label: "Project Name" },
      { code: "AMOUNT", label: "Amount" },
      { code: "CP_GEN_SUBCONTRACTOR_DP", label: "Subcontractor ID" },
      { code: "CP_SUB_SUBCONTRACTNO_TB", label: "Subcontract Number" },
      { code: "CP_SPA_SUBCONTRACTTYPE_PD", label: "Subcontract Type" },
      { code: "UE_INV_ORIGPOAMTCA", label: "Original PO Amount" },
      { code: "UE_INV_REVPOAMTABCA", label: "Revised PO Amount A+B" },
      { code: "UE_PO_POBALCDCA", label: "PO Balance C+D" },
      { code: "UE_GEN_SHORTDESCTB250", label: "Short Description" },
      { code: "UE_BLD_DETAILEDDESCMB4000", label: "Detailed Description" },
      { code: "CP_GEN_STATE_PD", label: "State" },
      { code: "CP_GEN_ADDRESS_TB2000", label: "Address" },
      { code: "CP_GEN_SUBCONTACTPHONE_TB64", label: "Contact Phone" },
      { code: "CP_SUB_PREFPAYMENTTERMS_PD", label: "Preferred Payment Terms" },
      { code: "UE_GEN_PAYMENTTERMSIPD", label: "Payment Terms" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXPOS_LINEITEM",
    displayName: "PO Line Items",
    description: "Line items within subcontractor purchase orders.",
    isLineItem: true,
    columns: [
      { code: "ID", label: "ID" },
      { code: "RECORD_ID", label: "Parent Record ID" },
      { code: "LI_NUM", label: "Line Item Number" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "SHORT_DESC", label: "Short Description" },
      { code: "AMOUNT", label: "Amount" },
      { code: "UUU_QUANTITY", label: "Quantity" },
      { code: "UUU_UNIT_PRICE", label: "Unit Price" },
      { code: "UUU_COSTED_QTY", label: "Costed Quantity" },
      { code: "UUU_COSTED_AMT", label: "Costed Amount" },
      { code: "UUU_NOT_COSTED_AMT", label: "Not-Costed Amount" },
      { code: "UE_GEN_UNITOFMEASURESPD", label: "Unit of Measure" },
      { code: "UUU_COST_LI_TYPE", label: "Cost Line Item Type" },
      { code: "GROUP_ID", label: "Group ID" },
      { code: "GROUP_TYPE", label: "Group Type" },
      { code: "BUDGETID", label: "Budget ID" },
      { code: "TASK_ID", label: "Task ID" },
      { code: "UUU_LI_LAST_UPDATE_DATE", label: "Last Updated" },
    ],
  },

  // ── Subcontractor Pay Applications ────────────────────────────────────────

  {
    tableName: "UNIFIER_UXSUM",
    displayName: "Subcontractor Pay Applications",
    description: "Subcontractor payment applications — completed work, retainage, and balance to finish.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "REFID", label: "Reference ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UUU_RECORD_LAST_UPDATE_DATE", label: "Last Updated" },
      { code: "UE_PRJ_PROJNAMESSN", label: "Project Name" },
      { code: "UE_PRJ_PROJNUMSSN", label: "Project Number" },
      { code: "CP_SUB_SUBCONTRACTNAME_TB50", label: "Subcontractor Name" },
      { code: "CP_GEN_SUBFIRSTNAME_TB64", label: "Contact First Name" },
      { code: "CP_GEN_SUBCONLASTNAME_TB64", label: "Contact Last Name" },
      { code: "CP_GEN_SUBCONTACTPHONE_TB64", label: "Contact Phone" },
      { code: "CP_GEN_ADDRESS_TB2000", label: "Address" },
      { code: "CP_GEN_CITY_TB50", label: "City" },
      { code: "CP_GEN_STATE_PD", label: "State" },
      { code: "CP_GEN_ZIP_TB16", label: "Zip Code" },
      { code: "CP_SUB_SUBCONTRACTNO_TB", label: "Subcontract Number" },
      { code: "CP_SPA_SUBCONTRACTTYPE_PD", label: "Subcontract Type" },
      { code: "CP_SPA_SUBPAYAPPNO_TB", label: "Sub Pay App Number" },
      { code: "AMOUNT", label: "Amount" },
      { code: "UE_CON_ORIGCOMMCA", label: "Original Commitment" },
      { code: "UE_CON_REVCOMMABCA", label: "Revised Commitment A+B" },
      { code: "UE_CON_TOTCOMPLSTRDCA", label: "Total Completed + Stored" },
      { code: "UE_CON_TOTWORKRETCA", label: "Total Work Retainage" },
      { code: "UE_CON_TOTRETEFCA", label: "Total Retainage EF" },
      { code: "UE_CON_TOTEARNEDLESSRETDGCA", label: "Total Earned Less Retainage D+G" },
      { code: "UE_CON_TOTPREVPAYMENTSCA", label: "Total Previous Payments" },
      { code: "UE_PYA_CURRPAYMENTDUE2CA", label: "Current Payment Due" },
      { code: "UE_CON_BALTOFININCLRETCA", label: "Balance to Finish (incl. Retainage)" },
      { code: "UE_CON_PCTAGECMPLTODTDCDA", label: "% Complete to Date" },
      { code: "UE_CON_WORKRETDA", label: "Work Retainage %" },
      { code: "UE_PYA_PERSTARTDO", label: "Period Start" },
      { code: "UE_PYA_PERENDDO", label: "Period End" },
      { code: "UE_INV_INVDATEDO", label: "Invoice Date" },
      { code: "UE_INV_PAYMENTDATEDO", label: "Payment Date" },
      { code: "UE_INV_PAYMENTDUEDATEDO", label: "Payment Due Date" },
      { code: "CP_INV_SUBINVNOTB128", label: "Sub Invoice Number" },
      { code: "UE_GEN_PAYMENTTERMSIPD", label: "Payment Terms" },
      { code: "CP_SUB_PREFPAYMENTTERMS_PD", label: "Preferred Payment Terms" },
      { code: "DUE_DATE", label: "Due Date" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXSUM_LINEITEM",
    displayName: "Pay Application Line Items",
    description: "Line items within subcontractor pay applications — SOV breakdown with % complete.",
    isLineItem: true,
    columns: [
      { code: "ID", label: "ID" },
      { code: "RECORD_ID", label: "Parent Record ID" },
      { code: "LI_NUM", label: "Line Item Number" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "SHORT_DESC", label: "Short Description" },
      { code: "AMOUNT", label: "Amount" },
      { code: "SCHEDULED_VALUE", label: "Scheduled Value" },
      { code: "UUU_QUANTITY", label: "Quantity" },
      { code: "UUU_UNIT_PRICE", label: "Unit Price" },
      { code: "UE_PYA_WORKPREVCOMPLCA", label: "Work Previously Completed" },
      { code: "UE_PYA_WORKCOMPLTHISPERCA", label: "Work Completed This Period" },
      { code: "UE_PYA_TOTCOMPLSTRDCA", label: "Total Completed + Stored" },
      { code: "UE_PYA_G2PCTAGECOMPLETEDA", label: "% Complete (G+2)" },
      { code: "UE_PYA_BALTOFINCA", label: "Balance to Finish" },
      { code: "UE_PYA_CURRPAYMENTDUECA", label: "Current Payment Due" },
      { code: "UE_PYA_WORKRETTHISPERCA", label: "Work Retainage This Period" },
      { code: "UE_PYA_TOTRETTODATECA", label: "Total Retainage to Date" },
      { code: "UE_CON_TOTWORKRETCA", label: "Total Work Retainage" },
      { code: "UE_PYA_TOTEARNEDLESSRETCA", label: "Total Earned Less Retainage" },
      { code: "UE_CON_WORKRETDA", label: "Work Retainage %" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "UUU_LI_LAST_UPDATE_DATE", label: "Last Updated" },
    ],
  },

  // ── P6 Activities ─────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_P6_ACTIVITY",
    displayName: "P6 Schedule Activities",
    description: "Oracle Primavera P6 schedule activities — planned and actual start/finish dates, WBS structure.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Unifier Project ID" },
      { code: "UUU_INT_P6_PROJECT_ID", label: "P6 Project ID" },
      { code: "UUU_P6ACTIVITYID", label: "P6 Activity ID" },
      { code: "UUU_P6ACTIVITYNAME", label: "Activity Name" },
      { code: "UUU_P6ACTIVITYTYPE", label: "Activity Type" },
      { code: "UUU_P6ACTIVITYSTATUS", label: "Activity Status" },
      { code: "UUU_P6WBSNAME", label: "WBS Name" },
      { code: "UUU_P6WBSPATH", label: "WBS Path" },
      { code: "UUU_P6PLANNEDSTART", label: "Planned Start" },
      { code: "UUU_P6PLANNEDFINISH", label: "Planned Finish" },
      { code: "UUU_P6REMAININGEARLYSTART", label: "Remaining Early Start" },
      { code: "UUU_P6REMAININGEARLYFINISH", label: "Remaining Early Finish" },
      { code: "UUU_P6START", label: "Actual Start" },
      { code: "UUU_P6FINISH", label: "Actual Finish" },
      { code: "UUU_ACTIVITY_LATE_START", label: "Late Start" },
      { code: "UUU_ACTIVITY_LATE_FINISH", label: "Late Finish" },
      { code: "CP_P6PRIM_CONSTR_DP", label: "P6 Constraint" },
      { code: "UUU_CREATEDATE", label: "Created Date" },
      { code: "UUU_LASTMODIFIED", label: "Last Modified" },
    ],
  },

  // ── Locations ─────────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXLOC",
    displayName: "Locations",
    description: "Unit/level/building location records per project — maps to project row building/level/unit.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UE_PRJ_PROJNAMESSN", label: "Project Name" },
      { code: "UE_PRJ_PROJNUMSSN", label: "Project Number" },
      { code: "CP_CI_UNIT_TB", label: "Unit" },
      { code: "CP_CI_UNIT_TYPE", label: "Unit Type" },
      { code: "CP_CI_BUILDING_PD", label: "Building" },
      { code: "CP_CI_LEVEL_IA", label: "Level (numeric)" },
      { code: "CP_CI_LEVEL_TB", label: "Level" },
      { code: "CP_CI_AREA_PD", label: "Area" },
      { code: "CP_CI_PHASE_TB", label: "Phase" },
      { code: "CP_CI_LOCATION", label: "Location" },
      { code: "CP_PHASE_PLAN_PD", label: "Phase Plan" },
    ],
  },

  // ── Material Approvals / Orders ────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXMA",
    displayName: "Material Approvals",
    description: "Material approval records per project.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "RECORD_NO", label: "Record Number" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "PROCESS_STATUS", label: "Process Status" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "AMOUNT", label: "Amount" },
      { code: "UUU_CREATION_DATE", label: "Created Date" },
      { code: "UE_PRJ_PROJNAMESSN", label: "Project Name" },
      { code: "UE_PRJ_PROJNUMSSN", label: "Project Number" },
    ],
  },

  {
    tableName: "UNIFIER_UXMA_LINEITEM",
    displayName: "Material Order Line Items",
    description: "Individual material line items — product details, ETA, delivery location, finish schedule.",
    isLineItem: true,
    columns: [
      { code: "ID", label: "ID" },
      { code: "RECORD_ID", label: "Parent Record ID" },
      { code: "LI_NUM", label: "Line Item Number" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "AMOUNT", label: "Amount" },
      { code: "UUU_QUANTITY", label: "Quantity" },
      { code: "UE_CD_UNITPRICECA", label: "Unit Price (CA)" },
      { code: "UE_GEN_UNITOFMEASURESPD", label: "Unit of Measure" },
      { code: "CP_FPL_PRODUCT_TB", label: "Product" },
      { code: "CP_FPL_MANUFACTURER_TB", label: "Manufacturer" },
      { code: "CP_FPL_COLOR_TB", label: "Color" },
      { code: "CP_FPL_SIZE_TB", label: "Size" },
      { code: "CP_FPL_FINISHSCHEDULE_TB", label: "Finish Schedule" },
      { code: "CP_FPL_SPECSECTION_TB", label: "Spec Section" },
      { code: "CP_FPL_REFERENCENUMBER_DA", label: "Reference Number" },
      { code: "CP_FPL_BIDQUANTITY_DA", label: "Bid Quantity" },
      { code: "CP_FPL_TOTALQUANTITY_DA", label: "Total Quantity" },
      { code: "CP_FPL_ORDEREDDATE_DOP", label: "Ordered Date" },
      { code: "CP_FPL_DROPDEADORDER_DOP", label: "Drop Dead Order Date" },
      { code: "CP_FPL_ETA_DOP", label: "ETA (Date)" },
      { code: "CP_FPL_ETA_TB", label: "ETA (Text)" },
      { code: "CP_FPL_DELIVERYLOCATION_TB", label: "Delivery Location" },
      { code: "CP_FPL_INSTALLATION_TB", label: "Installation Notes" },
      { code: "CP_FPL_INTERNALNOTES_TB", label: "Internal Notes" },
      { code: "CP_FPL_EXTERNALNOTES_TB", label: "External Notes" },
      { code: "CP_FPL_PRODUCTVERIFY_PD", label: "Product Verified" },
      { code: "CP_FPL_PRODUCTVERIFED_TB", label: "Product Verified Notes" },
      { code: "CP_SD_SHOPSTATUS_PD", label: "Shop Status" },
      { code: "CP_SD_SPECSTATUS_PD", label: "Spec Status" },
      { code: "CP_SD_SAMPLESSTATUS_PD", label: "Samples Status" },
      { code: "CP_OP_FDD_DOP", label: "Field Due Date" },
      { code: "UUU_LINE_ITEM_STATUS", label: "Line Item Status" },
      { code: "UE_SMT_LEADTIMEIA", label: "Lead Time" },
      { code: "UE_ACTIVITYPICKER", label: "Activity" },
      { code: "UUU_LI_LAST_UPDATE_DATE", label: "Last Updated" },
    ],
  },

  // ── Workflow ──────────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_SYS_PROCESS",
    displayName: "Workflow Processes",
    description: "Active and historical workflow process instances.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "SOURCE_ID", label: "Source Record ID" },
      { code: "SOURCE_TYPE_ID", label: "Source Type ID" },
      { code: "SOURCE_TYPE_NAME", label: "Source Type Name" },
      { code: "SOURCE_MODELNAME", label: "Source Model Name" },
      { code: "NAME", label: "Process Name" },
      { code: "TYPE", label: "Type" },
      { code: "STATUS", label: "Status" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "INITIATOR_ID", label: "Initiator ID" },
      { code: "START_DATE", label: "Start Date" },
      { code: "END_DATE", label: "End Date" },
      { code: "PLANNED_DURATION", label: "Planned Duration" },
      { code: "ACTUAL_DURATION", label: "Actual Duration" },
      { code: "ROUND", label: "Round" },
    ],
  },

  {
    tableName: "UNIFIER_SYS_TASK",
    displayName: "Workflow Tasks",
    description: "Individual workflow tasks assigned to users — pending approvals and actions.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "PROCESS_ID", label: "Process ID" },
      { code: "SOURCE_ID", label: "Source Record ID" },
      { code: "SOURCE_TYPE_ID", label: "Source Type ID" },
      { code: "ASSIGNEE_ID", label: "Assignee User ID" },
      { code: "NAME", label: "Task Name" },
      { code: "ACTION_NAME", label: "Action Name" },
      { code: "STATUS", label: "Status" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "START_DATE", label: "Start Date" },
      { code: "DUE_DATE", label: "Due Date" },
      { code: "END_DATE", label: "End Date" },
      { code: "ACTUAL_DURATION", label: "Actual Duration" },
      { code: "EMAILSENT", label: "Email Sent" },
      { code: "STEP_MASTER", label: "Step Master" },
      { code: "SENDERS", label: "Senders" },
      { code: "ROUND", label: "Round" },
      { code: "NID", label: "NID" },
      { code: "ACTIVE_LINK_ID", label: "Active Link ID" },
      { code: "TASK_NODE_ID", label: "Task Node ID" },
      { code: "PARENT_ID", label: "Parent ID" },
      { code: "SUBPROCESS_ID", label: "Subprocess ID" },
    ],
  },

  // ── Organization ──────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_US_XORG",
    displayName: "Organizations",
    description: "Organizational shells in Unifier.",
    columns: [
      { code: "PID", label: "Org ID" },
      { code: "UE_ORG_ORGNAMESSN", label: "Org Name" },
      { code: "UE_ORG_ORGNUMSSN", label: "Org Number" },
      { code: "DESCRIPTION", label: "Description" },
      { code: "UUU_SHELL_STATUS", label: "Status" },
    ],
  },

  // ── Login Usage ───────────────────────────────────────────────────────────

  {
    tableName: "SYS_LOGIN_USAGE",
    displayName: "Login Usage",
    description: "Tracks when users log in to Unifier — useful for cross-referencing active users.",
    columns: [
      { code: "USER_ID", label: "User ID" },
      { code: "LOGIN_DATE", label: "Login Date" },
      { code: "USAGE_HOUR", label: "Usage Hour" },
      { code: "PROJECT_ID", label: "Project ID" },
    ],
  },

  // ── Budget ────────────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_BUDGET",
    displayName: "Budgets",
    description: "Budget header records per project.",
    columns: [
      { code: "BUDGETID", label: "Budget ID" },
      { code: "PROJECTID", label: "Project ID" },
      { code: "BUDGETNAME", label: "Budget Name" },
      { code: "USERID", label: "Created By User ID" },
      { code: "COMPANYID", label: "Company ID" },
      { code: "TREEMODE", label: "Tree Mode" },
      { code: "CREATIONDATE", label: "Created Date" },
      { code: "MODIFIEDDATE", label: "Modified Date" },
    ],
  },

  {
    tableName: "UNIFIER_BUDGETITEM",
    displayName: "Budget Items",
    description: "Budget item (WBS code) definitions within a budget.",
    columns: [
      { code: "BITEMID", label: "Budget Item ID" },
      { code: "BUDGETID", label: "Budget ID" },
      { code: "CODE", label: "Code" },
      { code: "ITEM", label: "Item Name" },
      { code: "TYPEID", label: "Type ID" },
    ],
  },

  {
    tableName: "UNIFIER_BUDGETROW",
    displayName: "Budget Rows",
    description: "Budget row cost data — original costs, commitments, contract values, and margins.",
    columns: [
      { code: "BITEMID", label: "Budget Item ID" },
      { code: "BUDGETID", label: "Budget ID" },
      { code: "UXUEBCH_APPROVED", label: "Change Order (Approved)" },
      { code: "UXUECO_APPROVED", label: "Approved Contract Price Changes" },
      { code: "UXUECON_COMPLETED", label: "Original Contract Price" },
      { code: "UXUEIBU_APPROVED", label: "Estimated Cost (Budget)" },
      { code: "UXPOS_APPROVED", label: "As-Committed Cost 1" },
      { code: "UXPCO_APPROVED", label: "PCO Approved" },
      { code: "REB", label: "Current Budget Cost" },
      { code: "COMMITS", label: "Commitments" },
      { code: "COST1", label: "Estimated Gross Profit" },
      { code: "COST2", label: "Original Gross Margin" },
      { code: "COST3", label: "Current Contract Price" },
      { code: "COST4", label: "As-Committed Cost 2" },
      { code: "COST9", label: "Original Gross Profit" },
      { code: "COST10", label: "Original Gross Margin %" },
      { code: "COST11", label: "Changes Gross Profit" },
      { code: "COST12", label: "Changes Gross Margin %" },
      { code: "COST13", label: "Current Gross Profit" },
      { code: "COST14", label: "Current Gross Margin %" },
      { code: "COST15", label: "Gross Profit Variance" },
      { code: "COST16", label: "Gross Margin % Variance" },
      { code: "COST17", label: "Current Contract Price (Alt)" },
      { code: "COST20", label: "Current GP / Forecasted EAC GP" },
      { code: "COST21", label: "Current Gross Margin %" },
      { code: "COST24", label: "Estimated Cost" },
    ],
  },

  // ── Shop Drawing Requests ─────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXBSDR",
    displayName: "Build Shop Drawing Requests",
    description: "Build shop drawing request records — scope type, location, and material origin.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXFLSDR",
    displayName: "Flooring SD Requests",
    description: "Flooring shop drawing request records.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXFSDREV",
    displayName: "Floor SD Reviews",
    description: "Floor shop drawing review records.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXBREVP",
    displayName: "Build Shop Reviews",
    description: "Build shop drawing review records.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXBREVP_LINEITEM",
    displayName: "Build Shop Review Line Items",
    description: "Line items within build shop review records.",
    isLineItem: true,
    columns: [
      { code: "RECORD_ID", label: "Parent Record ID" },
      { code: "UUU_TAB_ID", label: "Tab ID" },
      { code: "CP_PHASE_PLAN_PD", label: "Phase Plan" },
      { code: "CP_SD_PHASE_DP", label: "SD Phase" },
    ],
  },

  // ── Purchase Orders (Material / Work) ─────────────────────────────────────

  {
    tableName: "UNIFIER_UXWORKO",
    displayName: "Flooring Purchase Orders",
    description: "Flooring purchase order records.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  {
    tableName: "UNIFIER_UXUEPO",
    displayName: "Purchase Orders",
    description: "General purchase order records.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "END_DATE", label: "End Date" },
      { code: "CP_PHASE_PLAN_PD", label: "Phase Plan" },
      { code: "CP_SD_PHASE_DP", label: "SD Phase" },
    ],
  },

  // ── Field Verification ────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXFLDVER",
    displayName: "Field Verification",
    description: "Field verification records.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CP_COSTWORKTYPE_PD", label: "Work Type" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "END_DATE", label: "End Date" },
    ],
  },

  // ── Build Shipping ────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER_UXBLDSP",
    displayName: "Build Shipping",
    description: "Build shipping records.",
    columns: [
      { code: "ID", label: "ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "CP_COST_SCOPETYPE_PD", label: "Scope Type" },
      { code: "CP_COST_LOCATION_PD", label: "Cost Location" },
      { code: "CP_COST_MATERIALORIGIN_PD", label: "Material Origin" },
      { code: "END_DATE", label: "End Date" },
      { code: "CP_PHASE_PLAN_PD", label: "Phase Plan" },
      { code: "CP_SD_PHASE_DP", label: "SD Phase" },
    ],
  },

  // ── Document Manager Views ────────────────────────────────────────────────
  // These are Unifier-generated views; column names confirmed by API error feedback.
  // Discovered via /api/devtools/unifier-metadata?tables=1

  {
    tableName: "BP_DM_FILE_VIEW",
    displayName: "DM File View",
    description: "Document Manager file view — files uploaded to Unifier per project.",
    columns: [
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "FILE_NAME", label: "File Name" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "FILE_SIZE", label: "File Size" },
      { code: "UPLOAD_DATE", label: "Upload Date" },
    ],
  },

  {
    tableName: "BP_DM_NODE_VIEW",
    displayName: "DM Node View",
    description: "Document Manager node view — folder/file nodes with download URLs.",
    columns: [
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "NODE_NAME", label: "Node Name" },
      { code: "NODE_TYPE", label: "Node Type" },
    ],
  },

  // ── Document Manager — company-level views (UNIFIER_ prefix) ─────────────
  // Mirrors of the BP_ project-level views. Same column set — add here so
  // the explorer doesn't fall back to columns:[] which Unifier rejects.

  {
    tableName: "UNIFIER_DM_FILE_VIEW",
    displayName: "DM File View (Company)",
    description: "Company-wide Document Manager file view. Same schema as BP_DM_FILE_VIEW.",
    columns: [
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "FILE_NAME", label: "File Name" },
      { code: "TITLE", label: "Title" },
      { code: "STATUS", label: "Status" },
      { code: "FILE_SIZE", label: "File Size" },
      { code: "UPLOAD_DATE", label: "Upload Date" },
    ],
  },

  {
    tableName: "UNIFIER_DM_NODE_VIEW",
    displayName: "DM Node View (Company)",
    description: "Company-wide Document Manager node view. Same schema as BP_DM_NODE_VIEW.",
    columns: [
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "NODE_NAME", label: "Node Name" },
      { code: "NODE_TYPE", label: "Node Type" },
    ],
  },

  {
    tableName: "UNIFIER_DM_NODE",
    displayName: "DM Node (Company)",
    description: "Company-wide DM node base table — may contain UUU_DOC_ATTRIBUTE_URL download links.",
    columns: [
      { code: "ID", label: "Node ID" },
      { code: "PARENT_ID", label: "Parent Node ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "NODE_NAME", label: "Node Name" },
      { code: "NODE_TYPE", label: "Node Type" },
      { code: "UUU_DOC_ATTRIBUTE_URL", label: "Download / Preview URL" },
      { code: "DESCRIPTION", label: "Description" },
    ],
  },

  // ── Document Manager (raw tables — mostly empty base tables) ──────────────

  {
    tableName: "unifier_dm_node",
    displayName: "DM Nodes (Download Links)",
    description: "Document Manager nodes — contains UUU_DOC_ATTRIBUTE_URL which holds the file download/preview link.",
    columns: [
      // Columns verified valid by the Unifier PDS API (invalid ones removed after testing)
      { code: "PARENT_ID", label: "Parent Node ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "NODE_NAME", label: "Node Name" },
      { code: "NODE_TYPE", label: "Node Type" },
      { code: "UUU_DOC_ATTRIBUTE_URL", label: "Download / Preview URL" },
      { code: "DESCRIPTION", label: "Description" },
    ],
  },

  {
    tableName: "unifier_dm_file",
    displayName: "DM Files",
    description: "Document Manager file records — metadata for files attached to Unifier records.",
    columns: [
      { code: "FILE_ID", label: "File ID" },
      { code: "NODE_ID", label: "Node ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "FILE_NAME", label: "File Name" },
      { code: "FILE_SIZE", label: "File Size" },
      { code: "FILE_TYPE", label: "File Type" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "CREATION_DATE", label: "Created Date" },
      { code: "LAST_MODIFIED_DATE", label: "Last Modified Date" },
      { code: "STATUS", label: "Status" },
      { code: "REVISION", label: "Revision" },
      { code: "TITLE", label: "Title" },
    ],
  },

  {
    tableName: "unifier_dm_file_content",
    displayName: "DM File Content",
    description: "Document Manager file content metadata — links files to their content/version records.",
    columns: [
      { code: "FILE_CONTENT_ID", label: "File Content ID" },
      { code: "FILE_ID", label: "File ID" },
      { code: "NODE_ID", label: "Node ID" },
      { code: "PROJECT_ID", label: "Project ID" },
      { code: "FILE_NAME", label: "File Name" },
      { code: "FILE_SIZE", label: "File Size" },
      { code: "FILE_TYPE", label: "File Type" },
      { code: "CREATOR_ID", label: "Creator ID" },
      { code: "CREATION_DATE", label: "Created Date" },
      { code: "REVISION", label: "Revision" },
      { code: "STATUS", label: "Status" },
    ],
  },

  // ── Scope List ────────────────────────────────────────────────────────────

  {
    tableName: "UNIFIER__CW_SLOW_LIST",
    displayName: "Scope List",
    description: "Scope work type lookup list.",
    columns: [
      { code: "TYPE", label: "Type" },
      { code: "DESC_ABRV", label: "Abbreviation" },
      { code: "LONG_DESC", label: "Long Description" },
    ],
  },
];

/** Look up a table definition by its Unifier table name. Returns undefined if not found. */
export function getTableDef(tableName: string): UnifierTableDef | undefined {
  return UNIFIER_SCHEMA.find((t) => t.tableName === tableName);
}

/** All allowlisted table names (for API query validation). */
export const ALLOWLISTED_TABLE_NAMES = new Set(UNIFIER_SCHEMA.map((t) => t.tableName));
